### PR TITLE
Add https support for cli tool

### PR DESCRIPTION
**Pull request by meowstars**
Hi Sam, or Max, or both,

This is just a little patch to handle https hosts in cli tool.  
It also adds an option to disable certificates check.

I want to emphasize that I am not fluent in coffeescript so my patch may appear ugly for more experienced devs but maybe it is worth submitting this as it may be useful.

Feel free to merge, trash, whatever this :)

Anyway, good job for this application.

### CODE REVIEW

**Comment by carsso** [comment]
I also need this patch, my 0bin instance is an https one :)

**Comment by zedentox** [comment]
+1

**Comment by sametmax** [comment]
TY

**Comment by meowstars** [comment]
Why not :) Thanks for merging!
I'm happy to see that people are interested in my patch.

**Pull request merged**
