### PR TITLE
Fix burn_after_reading feature, along with zerobin.py

### PR DESCRIPTION
**Pull request by Shir0kamii**
As promised, a quick fix to solve #81 and #90 

It also repairs zerobin.py

### CODE REVIEW

**Comment by zertrin** [comment]
Had the same issue today (after updating my 0bin for the first time since Jan 2013!), the fix worked for me :+1:

**Comment by Shir0kamii** [comment]
@sametmax Will you be able to merge it soon ?

**Comment by sametmax** [comment]
I apologize for being so slow.

I haven't forgotten, I'm seriously lazy with my github issues and they 
are stacking up.

**Comment by sametmax** [comment]
Ok, I have been way to trustful witht he quality of the pull request.

Going back on the history I realize:

- they break things;
- introduce external dependencies that were not discussed and not declared in setup.py or added in the libs dir;
- duplicate code;
- are not documented in the code or rst docs.

This is my fault for merging it without checking it seriously, not yours. I'm grateful people participate, I just need to do my job as a reviewer, which I didn't.

I will revert the commits up untill d47aa9536298c57bc038cb127ce523a93d8d66ff. From there, I will go back on any change and make cleaners merges.

**Comment by Shir0kamii** [comment]
Happy to see that you're back on 0bin :)

If you need me to modify code I wrote just tell me, I'll do it as soon as possible.

**Comment by sametmax** [comment]
Thank you so much. Again, this is my fault, not yours. You spent a lot of time on this, and I didn't.

**Comment by Shir0kamii** [comment]
It's nothing. In the open source world, we all give our free time. And I hope people understand that others can't be free all the time. Of course it's a bit of a hassle when it's the maintainer of a project but forks are here for good reasons.

As I said, I'm ready to help again. Even though I have less time than before, 0bin is a project I like and I want to support it as I can. Plus it's one of my first contributions to someone else's project so it have symbolic value. ;)

**Comment by sametmax** [comment]
Ok, i added HTTPS on 0bin.net, which was the more pressing issue. Now I'm going to look into these as well.

**Pull request merged**
