### PR TITLE
Use lockfile library instead of custom implementation

### PR DESCRIPTION
**Pull request by Shir0kamii**
I saw a TODO in the source code then I did it. Does it seems okay ?

### CODE REVIEW

**Comment by Natim** [comment]
Cool thanks

**Comment by sametmax** [comment]
Sweet ! Do you want to be added to the contributor file ?

**Comment by Shir0kamii** [comment]
Hello !

I'll gladly accept to be added. I think I will work on 0bin for a while because it's a middle sized project and I think it's a good opportunity to improve my coding skills.

Is there an issue or an improvement you want me to work on ?

**Comment by sametmax** [comment]
The most important and interesting issue is the admin page : https://github.com/sametmax/0bin/issues/87

**Pull request merged**
