### PR TITLE
FR #49 : make URL clickable automatically

### PR DESCRIPTION
**Pull request by BoboTiG**
A first try to make URL clickable automatically. What do you think?
The second commit will prevent XSS, in theory.

For better security, we could add a function callback to `content.replace` to check if there is at least one replacement. If so, then we use `$('#paste-content').html()` else `$('#paste-content').text()`.

### CODE REVIEW

**Comment by sametmax** [comment]
Have you checked if it work with HTML code paste such as http://0bin.net/paste/QOFtPlUYSmdpTLmL#F1Q14RcqqzlshPx6xMm+mSNLq80bdRSHWFwsWysrdt6 ? I haven't tried your code yet, but I feel like converting the URL inside would break it.

**Comment by BoboTiG** [comment]
It does not work with your example. I am working on that.

**Comment by BoboTiG** [comment]
This should be good. This solution works as:
1. Parse URL to a special pattern (`||a||` instead of `<a` and `||/||a>` for `</a>`)
2. Escape tag opener character (`<` to `&lt;`)
3. Replace pattern by tag opener character (`||a||` to `<a` and `||/||a>` to `</a>`)

It is not beautiful but it works.

**Comment by rugk** [comment]
Any news on this PR?

**Comment by auzias** [comment]
Does the URL parser avoid URL such as `file://`, [if you know what I mean](https://blog.steve.fi/If_your_code_accepts_URIs_as_input__.html) ?

**Pull request closed without merging**
